"""Tests for EvaluatePhase -- Brief-based L1-L5 evaluation."""
from __future__ import annotations

import pytest


def test_evaluate_build_brief_prompt():
    """Eval criteria from Brief should be included in the VLM prompt."""
    from vulca.studio.phases.evaluate import EvaluatePhase
    from vulca.studio.brief import Brief

    b = Brief.new("水墨山水")
    b.eval_criteria = {
        "L1": "Mountain-water composition with 20%+ negative space",
        "L2": "Ink brush texture quality and variation",
        "L3": "Fidelity to xieyi tradition techniques",
        "L4": "No cultural misrepresentation",
        "L5": "Convey serene contemplative mood",
    }

    phase = EvaluatePhase()
    prompt = phase.build_eval_prompt(b)

    assert "Mountain-water composition" in prompt
    assert "Ink brush texture" in prompt
    assert "L1" in prompt
    assert "L5" in prompt


def test_evaluate_fallback_without_criteria():
    """Without eval_criteria, should use tradition-based evaluation."""
    from vulca.studio.phases.evaluate import EvaluatePhase
    from vulca.studio.brief import Brief
    from vulca.studio.types import StyleWeight

    b = Brief.new("test", style_mix=[StyleWeight(tradition="chinese_xieyi", weight=1.0)])
    # No eval_criteria set

    phase = EvaluatePhase()
    prompt = phase.build_eval_prompt(b)

    # Should still produce a valid prompt using tradition
    assert "L1" in prompt
    assert len(prompt) > 50


def test_evaluate_auto_generates_criteria():
    """If Brief has no eval_criteria, EvaluatePhase should auto-generate them."""
    from vulca.studio.phases.evaluate import EvaluatePhase
    from vulca.studio.brief import Brief
    from vulca.studio.types import StyleWeight

    b = Brief.new("水墨山水", style_mix=[StyleWeight(tradition="chinese_xieyi", weight=1.0)])
    b.must_have = ["ink texture"]
    assert b.eval_criteria == {}

    phase = EvaluatePhase()
    phase.ensure_eval_criteria(b)

    assert "L1" in b.eval_criteria
    assert len(b.eval_criteria) == 5


@pytest.mark.asyncio
async def test_evaluate_with_mock():
    """EvaluatePhase should return scores even with mock (fallback)."""
    from vulca.studio.phases.evaluate import EvaluatePhase
    from vulca.studio.brief import Brief

    b = Brief.new("test evaluation")
    b.eval_criteria = {f"L{i}": f"Test criterion {i}" for i in range(1, 6)}

    phase = EvaluatePhase()
    # Use a fake image (will trigger fallback/mock scores)
    result = await phase.evaluate(b, image_path="", mock=True)

    assert result is not None
    assert "L1" in result
    assert all(isinstance(result[f"L{i}"], float) for i in range(1, 6))


# --- Step 1.1: Mock Scores with Variation (E2) ---


@pytest.mark.asyncio
async def test_mock_scores_differ_across_sessions():
    """Different sessions (different session_id) must produce different mock scores."""
    from vulca.studio.phases.evaluate import EvaluatePhase
    from vulca.studio.brief import Brief

    phase = EvaluatePhase()

    b1 = Brief.new("水墨山水")
    b1.eval_criteria = {f"L{i}": f"criterion {i}" for i in range(1, 6)}

    b2 = Brief.new("赛博朋克城市")
    b2.eval_criteria = {f"L{i}": f"criterion {i}" for i in range(1, 6)}

    # session_ids are generated by Brief.new(), so they differ
    assert b1.session_id != b2.session_id

    r1 = await phase.evaluate(b1, mock=True)
    r2 = await phase.evaluate(b2, mock=True)

    # At least one L-dimension score must differ between sessions
    scores_differ = any(r1[f"L{i}"] != r2[f"L{i}"] for i in range(1, 6))
    assert scores_differ, f"Scores identical across sessions: {r1} vs {r2}"


@pytest.mark.asyncio
async def test_mock_scores_differ_across_rounds():
    """Same session, different rounds must produce different mock scores."""
    from vulca.studio.phases.evaluate import EvaluatePhase
    from vulca.studio.brief import Brief
    from vulca.studio.types import GenerationRound

    phase = EvaluatePhase()

    b = Brief.new("水墨山水")
    b.eval_criteria = {f"L{i}": f"criterion {i}" for i in range(1, 6)}

    # Round 1: no generations yet
    r1 = await phase.evaluate(b, mock=True)

    # Simulate completing round 1
    b.generations.append(GenerationRound(
        round_num=1, image_path="round1.png", scores=r1,
    ))

    # Round 2: one generation in history
    r2 = await phase.evaluate(b, mock=True)

    scores_differ = any(r1[f"L{i}"] != r2[f"L{i}"] for i in range(1, 6))
    assert scores_differ, f"Scores identical across rounds: {r1} vs {r2}"


@pytest.mark.asyncio
async def test_mock_scores_respond_to_brief_completeness():
    """A more complete Brief should produce higher average mock scores."""
    from vulca.studio.phases.evaluate import EvaluatePhase
    from vulca.studio.brief import Brief
    from vulca.studio.types import Element, StyleWeight

    phase = EvaluatePhase()

    # Sparse Brief: only intent
    sparse = Brief.new("test")
    sparse.eval_criteria = {f"L{i}": f"criterion {i}" for i in range(1, 6)}

    # Rich Brief: many fields filled
    rich = Brief.new("test")
    rich.session_id = sparse.session_id  # same session_id to isolate completeness effect
    rich.mood = "serene"
    rich.style_mix = [StyleWeight(tradition="chinese_xieyi", weight=1.0)]
    rich.composition.layout = "rule-of-thirds"
    rich.palette.primary = ["#003366"]
    rich.elements = [Element(name="bamboo")]
    rich.must_have = ["ink texture"]
    rich.selected_concept = "mountain stream"
    rich.eval_criteria = {f"L{i}": f"criterion {i}" for i in range(1, 6)}

    r_sparse = await phase.evaluate(sparse, mock=True)
    r_rich = await phase.evaluate(rich, mock=True)

    avg_sparse = sum(r_sparse.values()) / 5
    avg_rich = sum(r_rich.values()) / 5

    assert avg_rich > avg_sparse, (
        f"Rich Brief avg ({avg_rich:.3f}) should be higher than sparse ({avg_sparse:.3f})"
    )


@pytest.mark.asyncio
async def test_mock_scores_within_valid_range():
    """All mock scores must be in [0.1, 0.95]."""
    from vulca.studio.phases.evaluate import EvaluatePhase
    from vulca.studio.brief import Brief

    phase = EvaluatePhase()

    # Run multiple sessions to check range
    for _ in range(10):
        b = Brief.new(f"test intent")
        b.eval_criteria = {f"L{i}": f"criterion {i}" for i in range(1, 6)}
        result = await phase.evaluate(b, mock=True)
        for dim in ("L1", "L2", "L3", "L4", "L5"):
            assert 0.1 <= result[dim] <= 0.95, (
                f"{dim}={result[dim]} out of range [0.1, 0.95]"
            )
